openapi: 3.0.2
info:
    title: books-api
    version: 1.0.0
    description: >-
        ### This is a Swagger UI for our Games API  \n\n### Error handling\nErrors are presented using the
        HTTP status codes 400-599. The response include a more detailed explanation about the error in the
        body.\n\n```\n{\n  \"error\": \"Cleartext explanation of the error that occurred\"\n}\n```\n\n###
        Generic API errors\nThese error responses can be returned by any of the described endpoints.\n\n| HTTP
        status  |  Description |\n|---|---|\n| 400| Bad input parameters or invalid request. More information
        can be found in the response body.\n| 401| The consumer does not have access to the requested resource
        or the provided token is not valid.\n| 404| The requested resource can not be found or the user does
        not have access to the resource.\n| 5XX| A server error has occurred while processing the request.
paths:
    /games:
        get:
            tags:
                - games
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                'List of games ':
                                    value:
                                        - Witcher 3
                                        - Cyberpunk 2077
                    description: Returns a list of games
            summary: 'GET: Get a list of all games.'
            description: 'GET: Returns a list of all games in API'
    '/games/{id}':
        get:
            tags:
                - details
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                full detaols of id games:
                                    value: >-
                                        {"id":1,"name":"Witcher 3","price":29.99},{"id":2,"name":"Cyberpunk
                                        2077","price":59.99},{"id":3,"name":"Minecraft","price":26.99}
                    description: |
                        Returns full details
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Game was not found in games array
            operationId: id
            summary: Get full details of game
            description: Returns a game in API
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message
